services:
  pg-customer:
    image: postgres:16
    container_name: pg-customer
    restart: unless-stopped
    environment:
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_pass
      POSTGRES_DB: customer_db
    ports:
      - "54320:5432"
    volumes:
      - pg-customer-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customer_user -d customer_db"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  pg-product:
    image: postgres:16
    container_name: pg-product
    restart: unless-stopped
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    ports:
      - "54330:5432"
    volumes:
      - pg-product-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  pg-order:
    image: postgres:16
    container_name: pg-order
    restart: unless-stopped
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    ports:
      - "54340:5432"
    volumes:
      - pg-order-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  pg-auth:
    image: postgres:16
    container_name: pg-auth
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "54350:5432"
    volumes:
      - pg-auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "56720:5672"
      - "56721:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 15s

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "59090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "53000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pg-customer-data:
  pg-product-data:
  pg-order-data:
  pg-auth-data:
  grafana-data:
