CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR NOT NULL CHECK (role IN ('ADMIN', 'ANALISTA', 'GERENTE', 'CLIENTE')),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);
