server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customers/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**,/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET:uma-chave-bem-longa-e-secreta-trocar-em-producao-0123456789}