server:
  port: 48761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # O Eureka Server, por padrão, também tenta se registrar como cliente
    # de si mesmo. Como ele É o servidor, isso não faz sentido aqui.
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
